### ISSUE TITLE
Canonical url does not refresh on navigation in SPA

### ISSUE THREAD

**Issue by kulsknight** [littlegiants/nuxt-canonical#1]
**Actual Behaviour** - While navigating through pages in a SPA, the canonical URL does not reflect the new route we've navigated to.
For example, if a user navigates from a page https://example.com/example1 (with canonical url as https://example.com/example1) to a page https://example.com/example2, the canonical URL on the new page still shows up as https://example.com/example1. The URL, however refreshes if we reload the page, or access it directly via the url.

**Expected Behaviour**: **_The change in canonical URL should be reflected as soon as we move to a new page, either via navigation, or via direct access._**

**Comment by DonnyMarsden** [comment]
@kulsknight whilst this could be fixed, is it necessary? Aren't canonical links purely for web crawlers requesting pages for the first time anyway?

**Comment by kulsknight** [comment]
> @kulsknight whilst this could be fixed, is it necessary? Aren't canonical links purely for web crawlers requesting pages for the first time anyway?

Hi @DonnyMarsden, thanks for the quick reply.
I do agree canonicals are meant for web crawlers, which might be accessing the pages just once, or even directly. But this fix might be necessary in scenarios where the javascript enabled crawlers index pages by navigating through links within the SPA, and render the canonical tags dynamically.
