### ISSUE TITLE
Does this package still works?

### ISSUE THREAD

**Issue by PatrykBielanin** [littlegiants/nuxt-canonical#9]
Hi, i installed your package, added config to **nuxt.config.js** and there's no output in my **head** tag. Does this package still works? Spent some time trying to figure it out and im curious if it's problem on my side.

**Comment by mpietrucha** [comment]
+1

**Comment by danielholst-lg** [comment]
I'll look into this, haven't used this is newly created nuxt projects lately

**Comment by pierrejarry** [comment]
Yes it does. You need to generate the project to be able to see it
